APP_NAME="{{APP_NAME}}"
APP_URL="{{APP_URL}}"
APP_KEY="{{APP_KEY}}"

DB_CONNECTION=mysql
DB_HOST="{{DB_HOST}}"
DB_PORT={{DB_PORT}}
DB_DATABASE="{{DB_DATABASE}}"
DB_USERNAME="{{DB_USERNAME}}"
DB_PASSWORD="{{DB_PASSWORD}}"
